### PR TITLE
Move events from internal to pkg

### PR DESCRIPTION
**Pull request by rdimitrov**
# Summary

The following PR moves events from internal to pkg

## Change Type

***Mark the type of change your PR introduces:***

- [ ] Bug fix (resolves an issue without affecting existing features)
- [ ] Feature (adds new functionality without breaking changes)
- [ ] Breaking change (may impact existing functionalities or require documentation updates)
- [ ] Documentation (updates or additions to documentation)
- [x] Refactoring or test improvements (no bug fixes or new functionality)

# Testing

***Outline how the changes were tested, including steps to reproduce and any relevant configurations. 
Attach screenshots if helpful.***

# Review Checklist:

- [x] Reviewed my own code for quality and clarity.
- [ ] Added comments to complex or tricky code sections.
- [ ] Updated any affected documentation.
- [ ] Included tests that validate the fix or feature.
- [ ] Checked that related changes are merged.

### CODE REVIEW

**Comment by JAORMX** [comment]
IMO we should move constructors and interfaces to pkg. But not the whole implementation.

**Comment by evankanderson** [comment]
Can we defer this until after #4784 ?

**Comment by rdimitrov** [comment]
> Can we defer this until after #4784 ?

Of course 👍 Do you have any idea how much time you'll need?

**Comment by evankanderson** [comment]
I'm guessing not more than 2-3 days

**Review by jhrozek — APPROVED** [review]
The newly exported interface looks minimal enough. I tried merging @evankanderson 's branch atop this one and while there were conflicts, they could be resolved quite easily (rename of events.Setup to eventer.New)

**Pull request merged**
